server:
  port: 8085

spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:fairchain}
    username: ${POSTGRES_USER:fairchain}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

fairchain:
  kafka:
    topic:
      pickup-event: pickup-event
      transport-event: transport-event
      warehouse-event: warehouse-event
      delivery-event: delivery-event
