ALTER TABLE auctions ADD COLUMN IF NOT EXISTS farmer_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS crop VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS region VARCHAR(128) NOT NULL DEFAULT '';
